language: node_js
node_js:
- 6
- 4
before_script:
- npm prune
script:
- npm run test
after_success:
- npm run ci:coveralls
before_deploy:
- npm run build
deploy:
  provider: npm
  on:
    repo: wikiwi/react-vendor-prefixer-provider
    tags: true
    node: 4
  skip_cleanup: true
  email: vinh@wikiwi.io
  api_key:
    secure: orMP6STVUvLY1HBY18dxe5jFQsCSxC/129DI4XPggTKHygVOvPbo7fSOS7QJXS/laTxOcFEy5XHUVXY8NekbMu3+9ggPOxhLIwHgY1uEgpBm3a0RJY7yZ6laKubHL7kQsKQwF71L2oWU5xoAu5upLidwB7yEpIdsaz241wo2j1nVOcqHFDUnr1id8kt6u77MG8KM6+Uw+KrpGrWctXXsqqb6o5j5RBx3xfauAOPtk+3+EcbtiGiudTBBPyKY37K0O+Ok0n10oJR0s2H5n8qVsV2KoPd3D5Di/BTTRYYUJaFu/ozSeORPYk+wjmBIyKEZc3VOUWkDY6h9ZtiDRqqRFCwIP43irUAAQ9DFvE3rOpIaBrhkDOakhMmlr7xwfYXfvS8VGXKWeLxUGZbIzIwT1yoHVNcFv0Lq1VThSyd8lV83FFXiRcMrWEQKcjYj3CDGDP+KZFP95jYCxTWULVxQZqP/DosyA6JxgObbohRCrhrIwgTWs+mccVaO7wB4jXLBGp8MqMsm2Rv0rBf8Jbt/GPX9FosqU6CdHQWcnWs16exFhUe3NlzkzzI36taPcN0MUL53TlYrw8ooe15RPOeeiZZcr3YAbTEJ9/5t8fyYQw6lVYe9G5wZMFuQNCDVMPIux4m7sTY6d0AJJZoWyIp2+30Z5d3CvupjRYo8RWVr+UY=
