language: node_js
node_js:
- 6
before_script:
- npm prune
script:
- npm run lint
- npm run test:coverage
- npm run build
after_success:
- npm run ci:coveralls
deploy:
  provider: npm
  on:
    repo: wikiwi/react-prefixer-provider
    tags: true
    node: 6
  skip_cleanup: true
  email: vinh@wikiwi.io
  api_key:
    secure: bYxSRObQ39DLt7jfCnPPFov6prCplHotnnmXyHShyXwdc8jNufwx38vmRFgYZ3igoUfyR06SuJ3gTMP22cpSxhpRb38HAv7wvmnFBi4fg7KH3Ppc2FNDCznKApKN+yfUEvHL+IbqrPtxGesVf4/WmmcYtPrpf4rVlYdrjcWNN2HUpejModjjmtv8Tl0wLH6WgbvYI5QBcAOwsOpmEQVjtejKuhNA4XJhXh0SaLQ9ePHYEn0g/8DRQWMc+9nbiMK5mh9Vpi/aEyj1Dd3bpikXLVQYK/9ADsaRotBtq4a2ypVV+FM2mNuNX5NdzuiEvbYDI2beWtZh83Y0TaRiC//RYAgzlUOtAdCs5nakz5uL9rRVdzcNhithMycTvDo8MXY1FRd8Qviyi4ukjtrJOBC0NSYWmqvC7SPhSr4rWkoZMmywp7gHKc2cf76/ey4GfS5lOQHDAteRGo/SlWNggSEEowSLYUFEgeMlAaY1SqKbNlh7tWz9q1OjQQFi7641lyRF3aiOersz9QIVjQOLG2GpNIbxqE/KwS/mA3/by1Nq7ZUaaz20/Vj8ZCFUcQRlQzs/104FOVDihZZ57Xf7mVIN0LKzrta8sv6UekShfO5J1NrLWqHLhjQSNVhg7aX3iVcXkbAorZ4Sz2rBh/OdBjJzCP8duXR0s6yzTR/8rXiiGis=
